fullnameOverride: api-gateway

replicaCount: 1

image:
  repository: ghcr.io/donghun0508/api-gateway
  tag: 903ec6e2ce2cda2725b1b97a295dc2408ce8845c
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: true
  className: traefik
  host: api.codecrew.site
  path: /
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: api-gateway-transport@kubernetescrd
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod

monitoring:
  enabled: true
  namespace: prometheus
  labels:
    release: prometheus
  path: /actuator/prometheus
  interval: 15s
  portName: http
