fullnameOverride: account-service

replicaCount: 1

image:
  repository: ghcr.io/donghun0508/account-service
  tag: 11a8a7cfd1addcf890f26eca99a7e413a3c9d7e0
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: false

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod

monitoring:
  enabled: true
  namespace: prometheus
  labels:
    release: prometheus
  path: /actuator/prometheus
  interval: 15s
  portName: http
