apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: world-server-fleet
  namespace: world-master-service
spec:
  replicas: 2
  scheduling: Packed
  strategy:
    type: RollingUpdate
  template:
    metadata:
      generateName: world-server-
      annotations:
        # Octops Ingress Configuration
        octops.io/gameserver-ingress-mode: "domain"
        octops.io/gameserver-ingress-domain: "game.codecrew.site"
        # Optional: TLS termination annotation if using a custom secret
        octops.io/terminate-tls: "false" 
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 7654
      template:
        spec:
          containers:
            - name: world-server
              image: ghcr.io/donghun0508/world-server:latest
              imagePullPolicy: Always
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "20m"
                limits:
                  memory: "128Mi"
                  cpu: "100m"
