apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: default
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: ".*-(prod|dev|staging)$"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    # This will be managed externally - this is just to add the annotation
