apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-gateway
  namespace: api-gateway
spec:
  encryptedData:
    ACCOUNT_SERVICE_URL: AgC2Q7cdytw+ye6uZZ5nQMjfldKYUtSUGAT4hHNWZsDULFG58N2TViGU0a6af8GaVeXEie0OAB8rNx90fp4ATaT+ACAdRxvtLvts30QIKvaGpXVe/Du1vnIcJ8pXL8MYZncETGBHif8nrMS/ksBIeVm0Ks37GBpEcCUjuhoe7agjsDomo6UIC8yRRj5hZwn5nDN81NC84B6MkACQbfYl0MnQYLStzkmJFmO+iboHUGCV0LtPjfFLdltFE5qpAu56zMkhkdqL/TuR41XdDdLqnfWZDI7S8aiRAPJavXF75UjC6fGMochGrAbu0mIyg+z9cUmynwBOv8pWuwRu2YIa8nvqlidE47AzS+h2B7gJVz5L1KohxEudtvbQP/vs1p+REX6/z5OT+KTGkslEt2mM0k4HZKmK7dzCFb9cejz0oAJBZX6HkEX4uPrQTl0e/tOBRHlSRCNmHyV53q+SoRP5Oq29pli1luPVv90USq47veZdikb8+pNroe9/rKc+ukx2PsIjUThF34tOe19JG3jy+wEGtVa8OnA7jGT2dlfyI7YkPxE9/05tTFf4iWCabhteOUpg3bML3VhOvBvL3OdsvZ7lhw8rGw0et9Z2AHVuwVTuZUv+UoYujnpBQxRxLBxw47wdSrrCXCZ5PLORKwSvAzP0aDL7s/HV/HNvTJGYTKsL1QowgtaqToRDq5bv6JzxWL2et2CYv3rE9fixJCZLL8TUGdaXns5JpZ888MnqST7M+yQTxuaLtK2GFss+
  template:
    metadata:
      name: api-gateway
      namespace: api-gateway
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: api-gateway
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: AgANAcCC0tNzwH90BY9GTzush2331ZRy97708A15fxsbu6dl6V4BQYjTVpLou13SBa0MjEqO7mtJ2lQR7vOfexSrdoJyX2JWFb3XT7cOzf6o8IpC4Pjgw5rhRNIrIktYRkbrGBCMgc78s4mv1RaWpelTOsyl/+A8N9RMDGMP9ooP2Z69pW/4OLrfHdNO34ilbH2BOuuR1ZF8pcgY/msSIVH/xUweM3W4WzV4m4zK6GQyiS0jjAlKLOMUs5gZQRiGPTM8ap2xb7/krdYG4Dr5YAnnRP6JvJebB7832qq6bTqn33vWont2g70z+PSGHkvG+mrmjbxoL3COZOmVqENstmE7sJ3wa0RXMa3gVCKBXWIqVWFndrj2mbL9YxsjLJyYiWPVmIE3yKxFWEXMXxGMf1Tjg4EFMPeGqFbrroCZgAftchg2mfRMFrjdSVI3q9mbkkMcXef/KT0ud3vgibLcw8PLc+wKETB6oVTGNczw4C9qPt9jBU92ZCJJRYZTdP2bnpJoEbbx9uN9HZqqQJgCs3BovSnHHGBFr+NJO0qQJBVQU47xRG5hn3BMBlAv3nhz9NWLmfrqLdZE3QQAhE/e4XJ+kfLkEXwixcSBvRQEahckHte09X1L+XzUVH2bcwktB9o6m51tVSlAkmskxvL+sWV1EJ+TZSEXNi0OmP7+1IT1ReJQ0Q1ADb5d/kfI8Juqh8jMUPfPAKB30jvVDOYYkVASOrSj6SD25TdXc7IEyyRsuJtVw2nARj19/64PglUqy88wgf9PPLdunHzQ2UDvsclMlwNyr8iWiSXeo7AMOEhDLX/AL39nMVak/wFX3YqUspRMohIo8PqqTZQldXL0DZJ183J0bFQlvQKzVXPwcpAI4C73h82H20zIsmU76Tc4U9/eZWsIka9tj0wCS74WeRmD2BrTNQb2l+71pjdpnbjdgzeFj76H1YQ5HOyFlPyTXX+G7wNLhSNAhvtme5icbjoMZO0=
  template:
    metadata:
      name: ghcr-secret
      namespace: api-gateway
    type: kubernetes.io/dockerconfigjson
