---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: redis
spec:
  encryptedData:
    redis-password: AgAgIE6LXKt/Q1FpnW86Ao+LQfSi/I/euW9ZEzeu80LGSIQnR4SO4LnyEBvSRYnQ6y5Xsx189UwjXnLX4Xwpou8mdqunpKkhL2QXnwiDi5QGEVhIDdJxIocE0Fq22ui95kVjXsLmqCiJ6Bd9xPkFNWdOSz6rVumoZk/6LrHUMEpVP/F2Aksfhogul6tNt+Wrv+h0p+SaspvN055FQN5f/BxA7xszPPOg5yatf5f1NZvkMSZQL1+V5cFt64nR2lHqMQeY++9OfY8liZoIoZnAaA8WpkAMZkS7hyb/Ey3+0t7XwPnLMZ/4zncaRRz3bNVkMISsuZQ5bHW4ZYz6Z0vz18vYxFXprsNulJjvjvhnG3qwRGYtKTL0xuSL+HoW6qqjwJe0p825EkDKs+6yomHcq8S7ZOFGrSuuNzmuIjUDwIXYAlDgBN/N/romyyDyNkNSIxNBm0JB7EeZalcJZ/QuA2DQXXt5o9M2niUKgPB8z21Zd0QAu4y9hjEIJmDxZ8j+0K21a48YWWfB38p1q+eH9Ms5TWRXQWLNxqARs/a2dJVQYhnUtYzhGJ8IEBn5hYQNdNM5RqSQ2DB9GkqRAenKNU7D0G0ANJRmGlEmYy+b9njdoERqmHsvsvCRHjEduGbfQeXH9dD9LmqvExvq6qZFj/wMUabTJuX03RrLf9lev5SMrzFOJy1EaydAMLC/2QZi9G/cEmSAyiO5zlU=
  template:
    metadata:
      name: redis-auth
      namespace: redis
    type: Opaque
