apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: mysql-outbox-connector
  namespace: kafka-prod
  labels:
    strimzi.io/cluster: kafka-connect
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    # MySQL Connection
    database.hostname: mysql.mysql.svc.cluster.local
    database.port: 3306
    database.user: ${file:/opt/kafka/external-configuration/debezium-mysql-credentials/debezium-user}
    database.password: ${file:/opt/kafka/external-configuration/debezium-mysql-credentials/debezium-password}

    # Topic prefix
    topic.prefix: codecrew

    # Capture all outbox tables from any database
    table.include.list: .*\.outbox

    # Schema history
    schema.history.internal.kafka.bootstrap.servers: kafka-cluster-kafka-bootstrap:9092
    schema.history.internal.kafka.topic: schema-changes.codecrew

    # Outbox Event Router SMT
    transforms: outbox
    transforms.outbox.type: io.debezium.transforms.outbox.EventRouter
    transforms.outbox.table.field.event.id: id
    transforms.outbox.table.field.event.key: aggregate_id
    transforms.outbox.table.field.event.type: event_type
    transforms.outbox.table.field.event.payload: payload
    transforms.outbox.table.field.event.timestamp: created_at
    transforms.outbox.route.topic.replacement: ${routedByValue}
    transforms.outbox.table.expand.json.payload: true

    # Snapshot mode
    snapshot.mode: initial

    # Tombstones
    tombstones.on.delete: false

    # Binary handling
    binary.handling.mode: base64
