apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: prometheus
            namespace: monitoring
            chart: kube-prometheus-stack
            repoURL: https://prometheus-community.github.io/helm-charts
            targetRevision: "80.4.1"
          - name: loki
            namespace: logging
            chart: loki
            repoURL: https://grafana.github.io/helm-charts
            targetRevision: "6.49.0"
          - name: promtail
            namespace: logging
            chart: promtail
            repoURL: https://grafana.github.io/helm-charts
            targetRevision: "6.17.1"

  template:
    metadata:
      name: "{{name}}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
        - group: ""
          kind: Service
          jqPathExpressions:
            - .metadata.labels
            - .metadata.annotations
        - group: ""
          kind: Secret
          name: prometheus-grafana
          namespace: monitoring
          jqPathExpressions:
            - .data
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[].failurePolicy

      sources:
        - repoURL: "{{repoURL}}"
          chart: "{{chart}}"
          targetRevision: "{{targetRevision}}"
          helm:
            valueFiles:
              - $values/infrastructure/{{name}}/values.yaml
        - repoURL: https://github.com/donghun0508/codecrew-gitops
          targetRevision: main
          ref: values

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - Replace=true
          - SkipDryRunOnMissingResource=true
          - SkipHooks=true