apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/donghun0508/codecrew-gitops
        revision: main
        files:
          - path: infrastructure/*/app.yaml

  template:
    metadata:
      name: "infra-{{name}}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      sources:
        - repoURL: "{{repo}}"
          chart: "{{chart}}"
          targetRevision: "{{version}}"
          helm:
            releaseName: "{{name}}"
            valueFiles:
              - $values/infrastructure/{{name}}/values.yaml

        - repoURL: https://github.com/donghun0508/codecrew-gitops
          targetRevision: main
          ref: values
          path: .

        - repoURL: https://github.com/donghun0508/codecrew-gitops
          targetRevision: main
          path: infrastructure/{{name}}
          directory:
            recurse: true
            exclude: "values.yaml"

      ignoreDifferences:
        - group: apps
          kind: StatefulSet
          jqPathExpressions:
            - .spec.volumeClaimTemplates[]?.metadata.annotations
            - .spec.template.metadata.annotations
        - group: ""
          kind: PersistentVolumeClaim
          jqPathExpressions:
            - .spec.volumeName
        - group: ""
          kind: Service
          jqPathExpressions:
            - .spec.clusterIP
            - .spec.clusterIPs

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
