apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-raw
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    # Helm chart 없는(순수 매니페스트) 케이스
    - git:
        repoURL: https://github.com/donghun0508/codecrew-gitops
        revision: main
        files:
          - path: "infrastructure/*/envs/*/app.yaml"
      selector:
        matchExpressions:
          - key: chart
            operator: DoesNotExist

  template:
    metadata:
      name: "infra-{{.name}}-{{index .path.segments 3}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{ or .syncWave "5" }}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      sources:
        - repoURL: https://github.com/donghun0508/codecrew-gitops
          targetRevision: main
          path: "{{index .path.segments 0}}/{{index .path.segments 1}}/{{index .path.segments 2}}/{{index .path.segments 3}}"
          directory:
            recurse: true
            exclude: "app.yaml,values.yaml"
      ignoreDifferences:
        - group: apps
          kind: StatefulSet
          jsonPointers:
            - /spec/volumeClaimTemplates
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
